apiVersion: apps/v1
kind: Deployment
metadata:
  name: protocol
spec:
  replicas: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      nodeSelector:
        pool: default
      volumes:
        - name: nginx-ssl
          secret:
            defaultMode: 420
            secretName: protocol-nginx-ssl
      containers:
        - name: protocol
          image: protocol:0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: nginx-ssl
              readOnly: true
