apiVersion: v1
kind: Service
metadata:
  name: protocol
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: protocol
